FROM golang:1.25-alpine AS builder  
  
WORKDIR /app  
COPY go.mod go.sum ./
RUN go mod download  
  
COPY . .  
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o publisher ./test/publisher/main.go  

FROM alpine:3.20
RUN apk --no-cache add ca-certificates  
WORKDIR /root/  
  
COPY --from=builder /app/publisher . 
ENTRYPOINT ["./publisher"]